"use client";
import axios from "axios";
import { VideoIcon } from "lucide-react";
import { useForm } from "react-hook-form";
import * as z from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";

import Heading from "@/components/heading";

import { formSchema } from "./constants";
import { Form, FormControl, FormField, FormItem } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Empty } from "@/components/empty";
import Loader from "@/components/loader";
import { useState } from "react";

const VideoPage = () => {
    const router = useRouter();
    const form = useForm<z.infer<typeof formSchema>>({
        resolver: zodResolver(formSchema),
        defaultValues: {
            prompt: "",
        }
    });

    const isLoading = form.formState.isSubmitting;

    const [video, setVideo] = useState<string>();

    const onSubmit = async (values: z.infer<typeof formSchema>) => {
        console.log(values);
        try {
            setVideo(undefined);
            const response = await axios.post("/api/video", values);
            setVideo(response.data);
            form.reset();
        } catch (error) {
            console.log(error);
            // Todo - Open Upgrade modal
        } finally {
            router.refresh();
        }
    }

    return (
        <div>
            <Heading
                title="Video Generation"
                description="Write your prompt and make it a video generated by AI."
                icon={VideoIcon}
                bgColor="bg-orange-700/10"
                iconColor="text-orange-700"
            />

            <div className="px-4 lg:px-8">
                <div>
                    <Form {...form}>
                        <form
                            onSubmit={form.handleSubmit(onSubmit)}
                            className="rounded-lg border w-full p-4 px-3 md:px-6 focus-within:shadow-sm grid grid-cols-12 gap-2"
                        >
                            <FormField
                                name="prompt"
                                render={({ field }) => (
                                    <FormItem className="col-span-12 lg:col-span-10 w-full">
                                        <FormControl className="m-0 p-0">
                                            <Input
                                                className="border-0 outline-none focus-visible:ring-0 focus-visible:ring-transparent"
                                                disabled={isLoading}
                                                placeholder="A goldfish in a deep ocean"
                                                {...field}
                                            />
                                        </FormControl>
                                    </FormItem>
                                )}
                            />

                            <Button
                                disabled={isLoading}
                                className="col-span-12 lg:col-span-2 w-full"
                                type="submit"
                            >
                                Generate
                            </Button>
                        </form>
                    </Form>
                </div>

                <div className="space-y-4 mt-8">

                    {
                        isLoading && (
                            <Loader />
                        )
                    }

                    {
                        !video && !isLoading && (
                            <Empty label="No video yet" />
                        )
                    }

                    {video && (
                        <video
                            className="w-full aspect-video rounded-lg border bg-black"
                            controls
                        >
                            <source src={video} />
                        </video>
                    )}
                </div>
            </div>
        </div>
    )
}

export default VideoPage;